enable_pi.

max_clauses(4).
max_vars(6).
max_body(4).
head_pred(outpix,4).
body_pred(inbelongs,4).
body_pred(objholes,3).

type(pair). type(obj).
type(coord). type(color). type(int).

type(outpix,(pair,coord,coord,color)).
type(inbelongs,(pair,obj,coord,coord)).
type(objholes,(pair,obj,int)).

direction(outpix,(in,in,in,out)).
direction(inbelongs,(in,out,in,in)).
direction(objholes,(in,in,out)).

body_pred(int_1,1).
type(int_1,(int,)).
direction(int_1,(out,)).
body_pred(int_2,1).
type(int_2,(int,)).
direction(int_2,(out,)).
body_pred(int_3,1).
type(int_3,(int,)).
direction(int_3,(out,)).
body_pred(int_4,1).
type(int_4,(int,)).
direction(int_4,(out,)).
body_pred(int_5,1).
type(int_5,(int,)).
direction(int_5,(out,)).
body_pred(int_6,1).
type(int_6,(int,)).
direction(int_6,(out,)).
body_pred(int_7,1).
type(int_7,(int,)).
direction(int_7,(out,)).
body_pred(int_8,1).
type(int_8,(int,)).
direction(int_8,(out,)).
body_pred(int_9,1).
type(int_9,(int,)).
direction(int_9,(out,)).
body_pred(int_0,1).
type(int_0,(int,)).
direction(int_0,(out,)).
body_pred(col_1,1).
type(col_1,(color,)).
direction(col_1,(out,)).
body_pred(col_2,1).
type(col_2,(color,)).
direction(col_2,(out,)).
body_pred(col_3,1).
type(col_3,(color,)).
direction(col_3,(out,)).
body_pred(col_4,1).
type(col_4,(color,)).
direction(col_4,(out,)).
body_pred(col_5,1).
type(col_5,(color,)).
direction(col_5,(out,)).
body_pred(col_6,1).
type(col_6,(color,)).
direction(col_6,(out,)).
body_pred(col_7,1).
type(col_7,(color,)).
direction(col_7,(out,)).
body_pred(col_8,1).
type(col_8,(color,)).
direction(col_8,(out,)).
body_pred(col_9,1).
type(col_9,(color,)).
direction(col_9,(out,)).
body_pred(col_0,1).
type(col_0,(color,)).
direction(col_0,(out,)).
